# Generated by Django 4.2.7 on 2024-06-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '002_alter_note_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteRelation',
            new_name='NoteDerivation',
        ),
    ]
