# Generated by Django 4.2.7 on 2024-06-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_rename_noterelation_notederivation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='note.note')),
                ('marked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='note.note')),
            ],
        ),
        migrations.DeleteModel(
            name='NoteDerivation',
        ),
    ]
