# Generated by Django 4.2.7 on 2024-06-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_notemark_delete_notederivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related',
            field=models.ManyToManyField(blank=True, null=True, to='note.note'),
        ),
    ]
