# Generated by Django 4.2.7 on 2024-06-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_note_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='related',
            field=models.ManyToManyField(blank=True, to='note.note'),
        ),
    ]
