# Generated by Django 4.2.7 on 2024-06-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_rename_notemark_notepointer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notepointer',
            old_name='mark',
            new_name='from_note',
        ),
        migrations.RenameField(
            model_name='notepointer',
            old_name='marked',
            new_name='to_note',
        ),
    ]
