# Generated by Django 4.2.7 on 2024-06-22 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_rename_mark_notepointer_from_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notepointer',
            name='from_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_note', to='note.note'),
        ),
        migrations.AlterField(
            model_name='notepointer',
            name='to_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_note', to='note.note'),
        ),
    ]
