# Generated by Django 4.2.7 on 2024-05-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0007_alter_requirement_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('status', models.CharField(choices=[('常态化', '常态化'), ('已取消', '已取消'), ('已完成', '已完成'), ('进行中', '进行中'), ('未开始', '未开始')], default='未开始', max_length=10, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='TodoRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_Todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_Todos', to='act.todo', verbose_name='源需求')),
                ('to_Todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_Todos', to='act.todo', verbose_name='衍生需求')),
            ],
        ),
        migrations.RemoveField(
            model_name='requirementrelationship',
            name='from_requirement',
        ),
        migrations.RemoveField(
            model_name='requirementrelationship',
            name='to_requirement',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='RequirementRelationship',
        ),
    ]
