# Generated by Django 4.2.5 on 2024-05-03 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('已完成', '已完成'), ('进行中', '进行中'), ('未开始', '未开始')], max_length=10, verbose_name='状态')),
                ('description', models.TextField(verbose_name='描述')),
                ('priority', models.IntegerField(verbose_name='优先级')),
                ('definitions', models.ManyToManyField(related_name='requirements', to='req_doc.definition', verbose_name='相关定义')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='req_doc.project', verbose_name='所属项目')),
            ],
        ),
        migrations.AddField(
            model_name='definition',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='req_doc.project', verbose_name='所属项目'),
        ),
    ]
