# Generated by Django 4.2.7 on 2024-05-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_doc', '0002_definition_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
    ]
