# Generated by Django 4.2.7 on 2024-05-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('req_doc', '0003_alter_definition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('已完成', '已完成'), ('进行中', '进行中'), ('未开始', '未开始')], default='未开始', max_length=10, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='笔记名称')),
                ('description', models.TextField(verbose_name='笔记')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='req_doc.project', verbose_name='所属项目')),
            ],
        ),
    ]
