# Generated by Django 4.2.5 on 2023-09-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='update_time',
        ),
    ]
