# Generated by Django 4.2.5 on 2023-09-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_remove_task_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=440),
        ),
    ]
