# Generated by Django 4.2.5 on 2024-05-03 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_definition_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(verbose_name='项目描述')),
            ],
        ),
        migrations.AddField(
            model_name='definition',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='plan.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='plan.project', verbose_name='所属项目'),
        ),
    ]
