# Generated by Django 4.2.5 on 2024-05-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_project_definition_project_requirement_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='definitions',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='project',
        ),
        migrations.DeleteModel(
            name='Definition',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
