# Generated by Django 4.2.7 on 2024-05-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='default_timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='Default Timezone'),
        ),
    ]
