# Generated by Django 4.2.7 on 2024-05-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_habit_default_timezone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habittrack',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habittrack',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
    ]
