# Generated by author on 2023-09-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_task_status'),
    ]

    operations = [

    ]
