# Generated by Django 4.2.5 on 2023-09-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_task_end_time_task_start_time_alter_task_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
