# Generated by Django 4.2.7 on 2024-05-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0002_requirement_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(null=True, verbose_name='笔记'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
    ]
