# Generated by Django 4.2.7 on 2024-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0003_alter_note_description_alter_requirement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
