# Generated by Django 4.2.7 on 2024-05-20 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0004_requirement_end_time_requirement_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='parent',
        ),
        migrations.CreateModel(
            name='RequirementRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_requirements', to='act.requirement')),
                ('to_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_requirements', to='act.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='act.RequirementRelationship', to='act.requirement', verbose_name='父需求'),
        ),
    ]
