# Generated by Django 4.2.7 on 2024-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0005_remove_requirement_parent_requirementrelationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='parents',
            field=models.ManyToManyField(through='act.RequirementRelationship', to='act.requirement', verbose_name='父需求'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('常态化', '常态化'), ('已取消', '已取消'), ('已完成', '已完成'), ('进行中', '进行中'), ('未开始', '未开始')], default='未开始', max_length=10, verbose_name='状态'),
        ),
    ]
