# Generated by Django 4.2.7 on 2024-05-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0008_todo_todorelationship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('mid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('fName', models.CharField(max_length=100, verbose_name='First Name')),
                ('hometown', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hometown')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='TodoPersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act.person', verbose_name='Person')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='act.todo', verbose_name='Todo')),
            ],
        ),
        migrations.CreateModel(
            name='SocialRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=10, verbose_name='Relationship')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_relationships', to='act.person', verbose_name='From Person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_relationships', to='act.person', verbose_name='To Person')),
            ],
        ),
    ]
