# Generated by Django 4.2.7 on 2024-05-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0009_person_todopersonrelation_socialrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('常态化', 'Normal'), ('已取消', 'Cancelled'), ('已完成', 'Completed'), ('进行中', 'In Progress'), ('未开始', 'Not Started')], default='未开始', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
