# Generated by Django 4.2.7 on 2024-05-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0011_person_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='todorelationship',
            name='from_status',
            field=models.CharField(choices=[('常态化', 'Normal'), ('已取消', 'Cancelled'), ('已完成', 'Completed'), ('进行中', 'In Progress'), ('未开始', 'Not Started')], default='未开始', max_length=10, verbose_name='From Status'),
        ),
        migrations.AddField(
            model_name='todorelationship',
            name='to_status',
            field=models.CharField(choices=[('常态化', 'Normal'), ('已取消', 'Cancelled'), ('已完成', 'Completed'), ('进行中', 'In Progress'), ('未开始', 'Not Started')], default='未开始', max_length=10, verbose_name='To Status'),
        ),
        migrations.AlterField(
            model_name='todorelationship',
            name='from_Todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_Todos', to='act.todo', verbose_name='Belong to'),
        ),
        migrations.AlterField(
            model_name='todorelationship',
            name='to_Todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_Todos', to='act.todo', verbose_name='Derived'),
        ),
    ]
