# Generated by Django 4.2.7 on 2024-05-27 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0012_todorelationship_from_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(choices=[('TelephoneNum', 'TelephoneNum'), ('Wechat', 'Wechat'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram')], max_length=50, verbose_name='Media')),
                ('account', models.CharField(max_length=100, verbose_name='Account')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_accounts', to='act.person', verbose_name='Person')),
            ],
        ),
    ]
