# Generated by Django 4.2.7 on 2024-05-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0013_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.CharField(choices=[('Linkin', 'Linkin'), ('TelephoneNum', 'TelephoneNum'), ('Wechat', 'Wechat'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram')], max_length=50, verbose_name='Media'),
        ),
    ]
