# Generated by Django 4.2.7 on 2024-06-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('act', '0014_alter_media_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
